<a href="https://colab.research.google.com/github/keishaqila/1007_data_science/blob/main/1007_Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

1. Create a numpy array of size 2 x 2

In [11]:
arr2x2 = np.array([[1, 2],
                 [3, 4]])
print("Array 2x2:\n",arr2x2)

Array 2x2:
 [[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [10]:
arr3x4 = np.random.rand(3,4)
print("Array 3x4:\n",arr3x4)

Array 3x4:
 [[0.22332326 0.45244173 0.47577371 0.98096265]
 [0.85518742 0.8482299  0.97480302 0.05940028]
 [0.77575577 0.33686006 0.36783121 0.53866405]]


3. Create a numpy array of ones and a numpy array of zeroes

In [12]:
array_ones = np.ones((2, 2))
array_zeros = np.zeros((2, 2))
print("Array of Ones:\n", array_ones)
print("Arry of Zeros:\n", array_zeros)

Array of Ones:
 [[1. 1.]
 [1. 1.]]
Arry of Zeros:
 [[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [13]:
arr6x3 = np.random.rand(6,3)
print("Array 6x3:\n", arr6x3)
transposed = np.transpose(arr6x3)
print("Transposed (3x6):\n", transposed)

Array 6x3:
 [[0.40242979 0.97670563 0.74191426]
 [0.26665179 0.98574645 0.72501271]
 [0.97966119 0.39579497 0.06073588]
 [0.26584156 0.84156652 0.36934758]
 [0.29865103 0.00337725 0.46008541]
 [0.98266259 0.03881618 0.70447373]]
Transposed (3x6):
 [[0.40242979 0.26665179 0.97966119 0.26584156 0.29865103 0.98266259]
 [0.97670563 0.98574645 0.39579497 0.84156652 0.00337725 0.03881618]
 [0.74191426 0.72501271 0.06073588 0.36934758 0.46008541 0.70447373]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [15]:
n = 2
p = 3
m = 4

A = np.random.rand(n, p)
B = np.random.rand(p, m)

dot_product = np.dot(A, B)
print("Array A (2x3):\n", A)
print("Array B (3x4):\n", B)
print("Dot product (2x4):\n", dot_product)

Array A (2x3):
 [[0.14444185 0.03141786 0.25336926]
 [0.92816624 0.57668707 0.97138363]]
Array B (3x4):
 [[0.42127422 0.21029352 0.64079317 0.59978486]
 [0.7144033  0.59222565 0.21460526 0.85015109]
 [0.03263946 0.33517896 0.23949277 0.63559917]]
Dot product (2x4):
 [[0.09156449 0.13390569 0.15997989 0.27438525]
 [0.83470509 0.86230358 0.95116202 1.66438182]]
